# Generated by Django 4.1.7 on 2023-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_edition',
            field=models.CharField(max_length=50),
        ),
    ]
