# Generated by Django 4.1.7 on 2023-12-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_rename_category_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_link',
            field=models.CharField(max_length=250),
        ),
    ]
